services:
  cassandra:
    image: cassandra:4.1.10
    container_name: cassandra
    restart: unless-stopped
    ports:
      - "${CASSANDRA_PORT}:${CASSANDRA_PORT}"
      - "7199:7199"
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - pizza-shop-network
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES'" ]
      interval: 30s
      timeout: 10s
      retries: 15

  menu-service:
    build: ./menu-service
    container_name: menu-service
    ports:
      - "${MENU_SERVICE_PORT}:${MENU_SERVICE_PORT}"
    environment:
      - SERVER_PORT=${MENU_SERVICE_PORT}
      - CASSANDRA_HOST=${CASSANDRA_HOST}
      - CASSANDRA_PORT=${CASSANDRA_PORT}
      - CASSANDRA_DATACENTER=datacenter1
      - CASSANDRA_KEYSPACE=menu
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - pizza-shop-network

networks:
  pizza-shop-network:
    driver: bridge

volumes:
  cassandra_data: