spring:
  application:
    name: menu-service

  cassandra:
    keyspace-name: menu
    contact-points: localhost:9042
    local-datacenter: datacenter1
    schema-action: create_if_not_exists
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    liquibase: DEBUG
    liquibase.executor: DEBUG
    com.ing.data.cassandra.jdbc: INFO