server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: menu-service

  cassandra:
    keyspace-name: menu
    contact-points: cassandra:9042
    local-datacenter: datacenter1
    schema-action: create_if_not_exists

logging:
  level:
    root: INFO
    liquibase: DEBUG
    liquibase.executor: DEBUG
    com.ing.data.cassandra.jdbc: INFO