server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: menu-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}

  cassandra:
    keyspace-name: ${CASSANDRA_KEYSPACE}
    contact-points: ${CASSANDRA_HOST}
    local-datacenter: ${CASSANDRA_DATACENTER}
    schema-action: create_if_not_exists
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    com.ing.data.cassandra.jdbc: INFO
aws:
  s3:
    bucket: ${S3_BUCKET}
    region: ${S3_REGION}
  credentials:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
